name: final_exam_app
description: "A new Flutter project for the take-home final exam."

# Prevent publishing to pub.dev
publish_to: 'none'

# Versioning
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  audioplayers: ^6.0.0
  shared_preferences: ^2.2.2
  provider: ^6.1.0
  firebase_core: ^2.30.0
  firebase_auth: ^4.17.3
  cloud_firestore: ^4.13.2

  # Optional for flip animations
  # flutter_flip_card: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/questions.json
    - assets/sounds/tick.mp3      # ✅ For ticking sound each second
    - assets/sounds/time_up.mp3   # ✅ For time up notification